<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

echo '<h2>Restoring All Database Content...</h2>';

try {
    $base_path = dirname(__DIR__);
    require $base_path . '/vendor/autoload.php';
    $app = require_once $base_path . '/bootstrap/app.php';
    $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
    $kernel->bootstrap();

    \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();

    // Restoring roles
    $rows = array (
  0 => 
  array (
    'id' => 1,
    'name' => 'SUPER_ADMIN',
    'display_name' => 'Super Admin',
    'hierarchy_level' => 0,
    'is_system' => 1,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-13 21:08:20',
    'updated_at' => '2026-09-13 21:08:20',
    'permissions' => NULL,
  ),
  1 => 
  array (
    'id' => 2,
    'name' => 'EMPLOYEE',
    'display_name' => 'Employee',
    'hierarchy_level' => 10,
    'is_system' => 1,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 12:20:20',
    'updated_at' => '2026-09-14 12:20:20',
    'permissions' => NULL,
  ),
  2 => 
  array (
    'id' => 3,
    'name' => 'CONTRIBUTOR',
    'display_name' => 'Contributor',
    'hierarchy_level' => 20,
    'is_system' => 0,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 18:12:08',
    'updated_at' => '2026-09-14 18:12:08',
    'permissions' => '["dashboard.view","tasks.own.view","tasks.own.work","tasks.comment","attendance.self","projects.view","notifications.in_app.view","profile.edit"]',
  ),
  3 => 
  array (
    'id' => 4,
    'name' => 'CEO',
    'display_name' => 'Chief Executive Officer',
    'hierarchy_level' => 10,
    'is_system' => 0,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 18:36:12',
    'updated_at' => '2026-09-14 18:36:12',
    'permissions' => '[]',
  ),
  4 => 
  array (
    'id' => 5,
    'name' => 'COO',
    'display_name' => 'Chief Operating Officer',
    'hierarchy_level' => 10,
    'is_system' => 0,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 18:36:12',
    'updated_at' => '2026-09-14 18:36:12',
    'permissions' => '[]',
  ),
  5 => 
  array (
    'id' => 6,
    'name' => 'PROJECT_MANAGER',
    'display_name' => 'Project Manager',
    'hierarchy_level' => 30,
    'is_system' => 0,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 18:36:12',
    'updated_at' => '2026-09-14 18:36:12',
    'permissions' => '[]',
  ),
  6 => 
  array (
    'id' => 7,
    'name' => 'TEAM_LEAD',
    'display_name' => 'Team Lead',
    'hierarchy_level' => 40,
    'is_system' => 0,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 18:36:12',
    'updated_at' => '2026-09-14 18:36:12',
    'permissions' => '[]',
  ),
  7 => 
  array (
    'id' => 8,
    'name' => 'HR',
    'display_name' => 'Human Resources',
    'hierarchy_level' => 40,
    'is_system' => 0,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 18:36:12',
    'updated_at' => '2026-09-14 18:36:12',
    'permissions' => '[]',
  ),
  8 => 
  array (
    'id' => 9,
    'name' => 'DESIGNER',
    'display_name' => 'Designer',
    'hierarchy_level' => 60,
    'is_system' => 0,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 18:36:12',
    'updated_at' => '2026-09-14 18:36:12',
    'permissions' => '[]',
  ),
  9 => 
  array (
    'id' => 10,
    'name' => 'DEVELOPER',
    'display_name' => 'Developer',
    'hierarchy_level' => 60,
    'is_system' => 0,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 18:36:12',
    'updated_at' => '2026-09-14 18:36:12',
    'permissions' => '[]',
  ),
  10 => 
  array (
    'id' => 11,
    'name' => 'QA',
    'display_name' => 'Quality Assurance',
    'hierarchy_level' => 60,
    'is_system' => 0,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 18:36:12',
    'updated_at' => '2026-09-14 18:36:12',
    'permissions' => '[]',
  ),
  11 => 
  array (
    'id' => 12,
    'name' => 'CLIENT',
    'display_name' => 'Client',
    'hierarchy_level' => 100,
    'is_system' => 0,
    'dashboard_widgets_json' => NULL,
    'sidebar_modules_json' => NULL,
    'created_by' => NULL,
    'created_at' => '2026-09-14 18:36:12',
    'updated_at' => '2026-09-14 18:36:12',
    'permissions' => '[]',
  ),
);
    foreach ($rows as $row) {
        \Illuminate\Support\Facades\DB::table('roles')->updateOrInsert(['name' => $row['name']], $row);
    }
    echo '<p style="color:green;">✅ Restored table: roles (' . count($rows) . ' rows)</p>';

    // Restoring departments
    $rows = array (
  0 => 
  array (
    'id' => 4,
    'code' => '011501',
    'name' => 'DIGITAL RADIO BANGLA',
    'organization' => 'Hexagon Kingdom',
    'created_at' => '2026-09-14 18:12:58',
    'updated_at' => '2026-09-14 18:12:58',
  ),
  1 => 
  array (
    'id' => 5,
    'code' => '012235',
    'name' => 'NeuraSoft LTD',
    'organization' => 'Hexagon Kingdom',
    'created_at' => '2026-09-14 18:12:58',
    'updated_at' => '2026-09-14 18:12:58',
  ),
  2 => 
  array (
    'id' => 6,
    'code' => '005203',
    'name' => 'HexagonLab Researcher',
    'organization' => 'Hexagon Kingdom',
    'created_at' => '2026-09-14 18:12:58',
    'updated_at' => '2026-09-14 18:12:58',
  ),
  3 => 
  array (
    'id' => 7,
    'code' => '001332',
    'name' => 'CosmoBangla',
    'organization' => 'Hexagon Kingdom',
    'created_at' => '2026-09-14 18:12:58',
    'updated_at' => '2026-09-14 18:12:58',
  ),
  4 => 
  array (
    'id' => 8,
    'code' => '013104',
    'name' => 'Intelligence Support',
    'organization' => 'Hexagon Kingdom',
    'created_at' => '2026-09-14 18:12:58',
    'updated_at' => '2026-09-14 18:12:58',
  ),
);
    foreach ($rows as $row) {
        \Illuminate\Support\Facades\DB::table('departments')->updateOrInsert(['id' => $row['id']], $row);
    }
    echo '<p style="color:green;">✅ Restored table: departments (' . count($rows) . ' rows)</p>';

    // Restoring users
    $rows = array (
  0 => 
  array (
    'id' => 1,
    'name' => 'Superhero',
    'full_name' => 'System Super Admin',
    'username' => 'superhero',
    'role' => 'SUPER_ADMIN',
    'role_id' => 1,
    'department_id' => 1,
    'whatsapp_number' => NULL,
    'phone' => NULL,
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'superadmin@neuragent.local',
    'email_verified_at' => '2026-09-13 21:08:21',
    'avatar' => 'avatars/QGRTBEfJJW9Wko7Qa2XkFgGGgvx5qFvEEVgGzCWH.jpg',
    'designation' => NULL,
    'joining_date' => NULL,
    'password' => '$2y$12$n8vQOSWzcJFQ4O0cGY7puusVFeRag3x3xZ5NiD2s9dVU1D0NIqg1W',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => 'VxBe4uDKznmXTS7souDPPJprVFcgckGWOLxOafDQ479gUhNG75x6NjdsfMlg',
    'created_at' => '2026-09-13 21:08:21',
    'updated_at' => '2026-09-14 17:42:08',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  1 => 
  array (
    'id' => 5,
    'name' => 'Md Imtiaz Ahmed Nahid',
    'full_name' => NULL,
    'username' => 'NAHID',
    'role' => 'SUPER_ADMIN',
    'role_id' => 1,
    'department_id' => 6,
    'whatsapp_number' => NULL,
    'phone' => NULL,
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'mdimtiazahmednahid@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => NULL,
    'joining_date' => NULL,
    'password' => '$2y$12$RqcIXo.u5lkEHZU45siNfOkjhsnnqsooigfwlXRCUa5RPdf9DaQ52',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 17:56:55',
    'updated_at' => '2026-09-14 18:36:06',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  2 => 
  array (
    'id' => 6,
    'name' => 'Jannat Ara Moon Moon',
    'full_name' => NULL,
    'username' => NULL,
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => NULL,
    'whatsapp_number' => NULL,
    'phone' => '01856277002',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'moon.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Senior Voice Artist',
    'joining_date' => NULL,
    'password' => '$2y$12$LKOZPx3p.hSrsWfWDOuFuOTbr9jZF7QnF.39Y4Rs/.l5.xU3inoAq',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:08',
    'updated_at' => '2026-09-14 18:12:08',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  3 => 
  array (
    'id' => 7,
    'name' => 'Sanzana Azad Purbasha Purbasha',
    'full_name' => NULL,
    'username' => NULL,
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => NULL,
    'whatsapp_number' => NULL,
    'phone' => '01977293949',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'purbasha.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Voice Artist',
    'joining_date' => NULL,
    'password' => '$2y$12$O8YubqoY2EWV5YX5PbO3y.5g6MzdNcBGAK1DM.d9hDmRYsi5Wi0fy',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:08',
    'updated_at' => '2026-09-14 18:12:08',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  4 => 
  array (
    'id' => 8,
    'name' => 'Maliha Zaman Mounota',
    'full_name' => NULL,
    'username' => NULL,
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => NULL,
    'whatsapp_number' => NULL,
    'phone' => '01323125303',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'maliha.hexagonlab@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Project Manager',
    'joining_date' => NULL,
    'password' => '$2y$12$qr0wvecpu0gh3Q51aD.r/uaEW.Qt7teF9DVLeEmUFFz/P/8VCw9h2',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:08',
    'updated_at' => '2026-09-14 18:12:08',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  5 => 
  array (
    'id' => 9,
    'name' => 'Anusha Rowshan Anusha',
    'full_name' => NULL,
    'username' => 'anusha',
    'role' => 'COO',
    'role_id' => 5,
    'department_id' => 4,
    'whatsapp_number' => NULL,
    'phone' => '01811495968',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'anusha.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Chief Operation Officer',
    'joining_date' => NULL,
    'password' => '$2y$12$hd6inPPUidduoBDrs4Y4me.ebT1qujO.cQ9Mzr6AWCzVzXDHmkpD.',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:09',
    'updated_at' => '2026-09-14 18:51:32',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  6 => 
  array (
    'id' => 10,
    'name' => 'Kazi Asifur Zaman Asif',
    'full_name' => NULL,
    'username' => 'asifur',
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => 4,
    'whatsapp_number' => NULL,
    'phone' => '01919888544',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'asifur.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Graphics Designer',
    'joining_date' => NULL,
    'password' => '$2y$12$xQaRafd8CaNsJOt7fYvQHeHobSa/pQr0EIlgY/AwDcNVTu19gyv5m',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:09',
    'updated_at' => '2026-09-14 18:36:35',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  7 => 
  array (
    'id' => 11,
    'name' => 'Shezan Ahammed Swadhin Swadhin',
    'full_name' => NULL,
    'username' => 'swadhin',
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => 4,
    'whatsapp_number' => NULL,
    'phone' => '01319141437',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'swadhin.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Editor',
    'joining_date' => NULL,
    'password' => '$2y$12$vQk8.LuAeJ3Twhs9HWLQV.Bj4gy4C0DO/sBHJI7D1Tv2ekV/VZmW2',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:09',
    'updated_at' => '2026-09-14 18:36:53',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  8 => 
  array (
    'id' => 12,
    'name' => 'Mohammad Tahzibul Islam Tamim Tamim',
    'full_name' => NULL,
    'username' => NULL,
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => NULL,
    'whatsapp_number' => NULL,
    'phone' => '01312135796',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'tamim.hexagonlab@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Editor',
    'joining_date' => NULL,
    'password' => '$2y$12$/HJX6YAVWoP.dl505OczLO6v4iaHER0RqMiqA0BMC3WQgQ89XC4US',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:09',
    'updated_at' => '2026-09-14 18:12:09',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  9 => 
  array (
    'id' => 13,
    'name' => 'MD Mutakabbir Siyam Siyam',
    'full_name' => NULL,
    'username' => NULL,
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => NULL,
    'whatsapp_number' => NULL,
    'phone' => '01331251717',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'siyam.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Editor & Designer',
    'joining_date' => NULL,
    'password' => '$2y$12$fEkol0ehDF8wGRx/HKJ2NOCwgwEtxfNLrSo.2cF.uqh1U3M172TjW',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:09',
    'updated_at' => '2026-09-14 18:12:09',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
);
    foreach ($rows as $row) {
        \Illuminate\Support\Facades\DB::table('users')->updateOrInsert(['email' => $row['email']], $row);
    }
    echo '<p style="color:green;">✅ Restored table: users (' . count($rows) . ' rows)</p>';

    // Restoring projects
    $rows = array (
  0 => 
  array (
    'id' => 5,
    'name' => 'Digital Radio Bangla | AudioBook',
    'description' => 'Digital Radio Bangla | AudioBook',
    'status' => 'ACTIVE',
    'priority' => 'HIGH',
    'start_date' => NULL,
    'end_date' => NULL,
    'owner_id' => 1,
    'progress' => 0,
    'color_code' => NULL,
    'created_by' => 1,
    'created_at' => '2026-09-14 18:46:45',
    'updated_at' => '2026-09-14 18:47:04',
  ),
);
    foreach ($rows as $row) {
        \Illuminate\Support\Facades\DB::table('projects')->updateOrInsert(['id' => $row['id']], $row);
    }
    echo '<p style="color:green;">✅ Restored table: projects (' . count($rows) . ' rows)</p>';

    // Restoring project_members
    $rows = array (
  0 => 
  array (
    'id' => 4,
    'project_id' => 5,
    'user_id' => 9,
    'role' => 'LEAD',
    'status' => 'ACTIVE',
    'created_at' => '2026-09-14 18:55:22',
    'updated_at' => '2026-09-14 18:55:22',
  ),
  1 => 
  array (
    'id' => 5,
    'project_id' => 5,
    'user_id' => 6,
    'role' => 'VOICE ARTIST',
    'status' => 'ACTIVE',
    'created_at' => '2026-09-14 18:56:39',
    'updated_at' => '2026-09-14 18:56:39',
  ),
  2 => 
  array (
    'id' => 6,
    'project_id' => 5,
    'user_id' => 11,
    'role' => 'WRITER',
    'status' => 'ACTIVE',
    'created_at' => '2026-09-14 18:56:52',
    'updated_at' => '2026-09-14 18:56:52',
  ),
  3 => 
  array (
    'id' => 7,
    'project_id' => 5,
    'user_id' => 5,
    'role' => 'LEAD',
    'status' => 'ACTIVE',
    'created_at' => '2026-09-14 18:57:00',
    'updated_at' => '2026-09-14 18:57:00',
  ),
  4 => 
  array (
    'id' => 8,
    'project_id' => 5,
    'user_id' => 10,
    'role' => 'EDITOR',
    'status' => 'ACTIVE',
    'created_at' => '2026-09-14 18:57:10',
    'updated_at' => '2026-09-14 18:57:10',
  ),
);
    foreach ($rows as $row) {
        \Illuminate\Support\Facades\DB::table('project_members')->updateOrInsert(['id' => $row['id']], $row);
    }
    echo '<p style="color:green;">✅ Restored table: project_members (' . count($rows) . ' rows)</p>';

    \Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();
    echo '<h3 style="color:blue;">🎉 All data restored successfully!</h3>';
} catch (\Exception $e) {
    echo '<h3 style="color:red;">🚨 Error:</h3>';
    echo '<p>' . $e->getMessage() . '</p>';
}
