<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

echo '<h2>Restoring Previous Users...</h2>';

try {
    $base_path = dirname(__DIR__);
    require $base_path . '/vendor/autoload.php';
    $app = require_once $base_path . '/bootstrap/app.php';
    $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
    $kernel->bootstrap();

    $users = array (
  0 => 
  array (
    'id' => 5,
    'name' => 'Md Imtiaz Ahmed Nahid',
    'full_name' => NULL,
    'username' => 'NAHID',
    'role' => 'SUPER_ADMIN',
    'role_id' => 1,
    'department_id' => 6,
    'whatsapp_number' => NULL,
    'phone' => NULL,
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'mdimtiazahmednahid@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => NULL,
    'joining_date' => NULL,
    'password' => '$2y$12$RqcIXo.u5lkEHZU45siNfOkjhsnnqsooigfwlXRCUa5RPdf9DaQ52',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 17:56:55',
    'updated_at' => '2026-09-14 18:36:06',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  1 => 
  array (
    'id' => 6,
    'name' => 'Jannat Ara Moon Moon',
    'full_name' => NULL,
    'username' => NULL,
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => NULL,
    'whatsapp_number' => NULL,
    'phone' => '01856277002',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'moon.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Senior Voice Artist',
    'joining_date' => NULL,
    'password' => '$2y$12$LKOZPx3p.hSrsWfWDOuFuOTbr9jZF7QnF.39Y4Rs/.l5.xU3inoAq',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:08',
    'updated_at' => '2026-09-14 18:12:08',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  2 => 
  array (
    'id' => 7,
    'name' => 'Sanzana Azad Purbasha Purbasha',
    'full_name' => NULL,
    'username' => NULL,
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => NULL,
    'whatsapp_number' => NULL,
    'phone' => '01977293949',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'purbasha.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Voice Artist',
    'joining_date' => NULL,
    'password' => '$2y$12$O8YubqoY2EWV5YX5PbO3y.5g6MzdNcBGAK1DM.d9hDmRYsi5Wi0fy',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:08',
    'updated_at' => '2026-09-14 18:12:08',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  3 => 
  array (
    'id' => 8,
    'name' => 'Maliha Zaman Mounota',
    'full_name' => NULL,
    'username' => NULL,
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => NULL,
    'whatsapp_number' => NULL,
    'phone' => '01323125303',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'maliha.hexagonlab@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Project Manager',
    'joining_date' => NULL,
    'password' => '$2y$12$qr0wvecpu0gh3Q51aD.r/uaEW.Qt7teF9DVLeEmUFFz/P/8VCw9h2',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:08',
    'updated_at' => '2026-09-14 18:12:08',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  4 => 
  array (
    'id' => 9,
    'name' => 'Anusha Rowshan Anusha',
    'full_name' => NULL,
    'username' => 'anusha',
    'role' => 'COO',
    'role_id' => 5,
    'department_id' => 4,
    'whatsapp_number' => NULL,
    'phone' => '01811495968',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'anusha.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Chief Operation Officer',
    'joining_date' => NULL,
    'password' => '$2y$12$hd6inPPUidduoBDrs4Y4me.ebT1qujO.cQ9Mzr6AWCzVzXDHmkpD.',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:09',
    'updated_at' => '2026-09-14 18:51:32',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  5 => 
  array (
    'id' => 10,
    'name' => 'Kazi Asifur Zaman Asif',
    'full_name' => NULL,
    'username' => 'asifur',
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => 4,
    'whatsapp_number' => NULL,
    'phone' => '01919888544',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'asifur.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Graphics Designer',
    'joining_date' => NULL,
    'password' => '$2y$12$xQaRafd8CaNsJOt7fYvQHeHobSa/pQr0EIlgY/AwDcNVTu19gyv5m',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:09',
    'updated_at' => '2026-09-14 18:36:35',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  6 => 
  array (
    'id' => 11,
    'name' => 'Shezan Ahammed Swadhin Swadhin',
    'full_name' => NULL,
    'username' => 'swadhin',
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => 4,
    'whatsapp_number' => NULL,
    'phone' => '01319141437',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'swadhin.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Editor',
    'joining_date' => NULL,
    'password' => '$2y$12$vQk8.LuAeJ3Twhs9HWLQV.Bj4gy4C0DO/sBHJI7D1Tv2ekV/VZmW2',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:09',
    'updated_at' => '2026-09-14 18:36:53',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  7 => 
  array (
    'id' => 12,
    'name' => 'Mohammad Tahzibul Islam Tamim Tamim',
    'full_name' => NULL,
    'username' => NULL,
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => NULL,
    'whatsapp_number' => NULL,
    'phone' => '01312135796',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'tamim.hexagonlab@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Editor',
    'joining_date' => NULL,
    'password' => '$2y$12$/HJX6YAVWoP.dl505OczLO6v4iaHER0RqMiqA0BMC3WQgQ89XC4US',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:09',
    'updated_at' => '2026-09-14 18:12:09',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
  8 => 
  array (
    'id' => 13,
    'name' => 'MD Mutakabbir Siyam Siyam',
    'full_name' => NULL,
    'username' => NULL,
    'role' => 'CONTRIBUTOR',
    'role_id' => 3,
    'department_id' => NULL,
    'whatsapp_number' => NULL,
    'phone' => '01331251717',
    'phone_number' => NULL,
    'normalized_phone_number' => NULL,
    'email' => 'siyam.digitalradiobangla@gmail.com',
    'email_verified_at' => NULL,
    'avatar' => NULL,
    'designation' => 'Editor & Designer',
    'joining_date' => NULL,
    'password' => '$2y$12$fEkol0ehDF8wGRx/HKJ2NOCwgwEtxfNLrSo.2cF.uqh1U3M172TjW',
    'status' => 'ACTIVE',
    'contribution_points' => 0,
    'productivity_score' => 0,
    'reliability_score' => 0,
    'execution_score' => 0,
    'is_default_password' => 1,
    'must_change_password' => 1,
    'password_changed_at' => NULL,
    'is_active' => 1,
    'suspended_at' => NULL,
    'last_login_at' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'remember_token' => NULL,
    'created_at' => '2026-09-14 18:12:09',
    'updated_at' => '2026-09-14 18:12:09',
    'two_factor_secret' => NULL,
    'two_factor_recovery_codes' => NULL,
    'two_factor_confirmed_at' => NULL,
    'bank_account_details' => NULL,
    'mobile_banking_details' => NULL,
  ),
);

    foreach ($users as $u) {
        // Clean up the array to remove nulls or specific IDs if needed, though ID preservation is good.
        $exists = \App\Models\User::where('email', $u['email'])->first();
        if (!$exists) {
            \App\Models\User::insert($u);
            echo '<p style="color:green;">✅ Restored user: ' . $u['name'] . '</p>';
        } else {
            echo '<p style="color:orange;">⚠️ User already exists: ' . $u['name'] . '</p>';
        }
    }
    echo '<h3 style="color:blue;">🎉 All previous users have been restored successfully!</h3>';
} catch (\Exception $e) {
    echo '<h3 style="color:red;">🚨 Error:</h3>';
    echo '<p>' . $e->getMessage() . '</p>';
}
